export let Attractions = ['vøringsfossen','voringsfossen','voring waterfall','trollstigen','troll','troll road','kjos','kjosfossen',
'kjos waterfall','geiranger','geirangerfjorden','geiranger fjord','stalheimkleivene','nærøy','nærøy fjord','sognefjellsvegen','sognefjord',
'sogne','steinsdal','steinsdalsfossen','steinsdal waterfall','atlanterhavsveien','atlantic road','tvinde','tvindefossen','tvinde waterfall',
'briksdal','briksdalsbreen','briksdal glacier','drammen','stavkirke','stave church','lutefisk','fisk','gudvangen','norge','norway','lofoten',
'fjellstua','aksla','fjellstua viewpoint','aksla viewpoint','dalsnibba','dalsnibba summit','bøyabreen','boyabreen','northern lights','svalbard',
'boya glacier','telemark','telemarkskanalen','telemark canal','preikestolen','pulpit rock','lysefjorden','lysefjord','laks','rjukan','isbjørn',
'laksfossen','laks waterfall','salmon waterfall','bratte','fossen','bratte fossen','bratte waterfall','steep waterfall','verdens ende',
'lindesnes','lindesnes fyr','lindesnes lighthouse','nigard','nigardsbreen','nigard glacier','torghatten','torg','norlys','geilo','polar bear',
'torghatten mountain','besseggen','besseggen ridge','kjendal','kjenndalsbreen','kjenndal glacier','holmenkollen','nor','nord','north','jan mayen',
'holmenkollbakken','kristiansand','kristiansand dyrepark','kristiansand zoo','tusenfryd','tusenfryd amusement park','fløibanen','ski','bouvet',
'floibanen','floibanen funicular railway','fløyen','floyen','hadeland glassverk','hadeland glass factory','hadeland','beitostølen','breen',
'flåmsbanen','flamsbanen','flam railway','flam line','flåm','vikingskipshuset','viking ship museum','viking','aurora borealis','dal','ice',
'nidaros domkirke','nidaros','nidaros cathedral','lysgårdsbakken','Lysgardsbakken','lysgård ski jump','lysgård','reindeer','elk','glacier',
'nordkapphallen','nordkapp','north cape hall','north cape','maihaugen','maihaugen open air museum','byrkjedalstunet','elg','lærdal','boller',
'byrkjedalstunet hotel','ishavskatedralen','arctic cathedral','troms','tromsdalen','fjellheisen','fjellheisen tramway','fjell','fjord',
'hardangervidda natursenter','hardangervidda','hardangervidda nasjonalparken','atlanterhavsparken','hardanger','reinsdyr','aurland',
'atlantic aquarium','polaria','polaria aquarium','lom','lom stavkirke','lom stave church','oslo','bergen','akershus','hjemet','bunad',
'stavanger','trondheim','kristiansand','tromso','tromsø','ålesund','alesund','bodø','lillehammer','trolltunga','huset','hjem','norsk',
'mo i rana','alta','narwik','narvik','røros','roros','trolltunga','jotunheimen','jotunheimen mountains','eidsvoll','cross country skiing']
